# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

strategy:
  matrix:
    linux6:
      imageName: "ubuntu-latest"
      dotnetversion: "6.0.x"

    linux8:
      imageName: "ubuntu-latest"
      dotnetversion: "8.0.x"
    mac8:
      imageName: "macOS-latest"
      dotnetversion: "8.0.x"
    mac6:
      imageName: "macOS-latest"
      dotnetversion: "6.0.x"
  maxParallel: 2

pool:
  vmImage: $(imageName)



  stages:
   - stage: TEST
     jobs:
      - job: Installtool
        displayName: Install .NET SDK
        steps:
         - task: UseDotNet@2
           inputs:
           packageType: 'sdk'
           version: $(dotnetversion)